### PR TITLE
Fixing issue with import map. Resolves #30.

### LINKED ISSUE #30: Cannot use import statement outside a module
I'm new using single-spa and I've been trying to put a create-single-spa react application inside my root config (also created with the CLI), I'm not doing any modification, just putting the import map taken for the playground and my app crashes!

### PR DESCRIPTION
**Pull request by joeldenning**
See #30

### CODE REVIEW

**Comment by joeldenning** [comment]
cc @Sauloxd

File: src/root-config-guide/root-config-guide.component.js [hunk 1]
```diff
@@ -35,10 +35,12 @@ export default function HtmlFile(props) {
     );
 
   const importMap = {
-    [application.name]: window.importMapOverrides.getOverrideMap().imports[
-      application.name
-    ],
-    ...sharedDepsImportMap(application.sharedDeps),
+    imports: {
```
Comment (joeldenning) [inline src/root-config-guide/root-config-guide.component.js:38]: Import maps need the imports top level property
